/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EventsRouteImport } from './routes/events'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSihInternalHackathonRouteRouteImport } from './routes/events.sih-internal-hackathon.route'
import { Route as MemberSlugRouteImport } from './routes/member.$slug'
import { Route as EventsSihInternalHackathonIndexRouteImport } from './routes/events.sih-internal-hackathon.index'
import { Route as EventsSihInternalHackathonJoinRouteImport } from './routes/events.sih-internal-hackathon.join'
import { Route as EventsSihInternalHackathonTeamRouteImport } from './routes/events.sih-internal-hackathon.team'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsSihInternalHackathonRouteRoute =
  EventsSihInternalHackathonRouteRouteImport.update({
    id: '/sih-internal-hackathon',
    path: '/sih-internal-hackathon',
    getParentRoute: () => EventsRoute,
  } as any)
const MemberSlugRoute = MemberSlugRouteImport.update({
  id: '/member/$slug',
  path: '/member/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSihInternalHackathonIndexRoute =
  EventsSihInternalHackathonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EventsSihInternalHackathonRouteRoute,
  } as any)
const EventsSihInternalHackathonJoinRoute =
  EventsSihInternalHackathonJoinRouteImport.update({
    id: '/join',
    path: '/join',
    getParentRoute: () => EventsSihInternalHackathonRouteRoute,
  } as any)
const EventsSihInternalHackathonTeamRoute =
  EventsSihInternalHackathonTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => EventsSihInternalHackathonRouteRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/projects': typeof ProjectsRoute
  '/events/sih-internal-hackathon': typeof EventsSihInternalHackathonRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/member/$slug': typeof MemberSlugRoute
  '/events/': typeof EventsIndexRoute
  '/events/sih-internal-hackathon/join': typeof EventsSihInternalHackathonJoinRoute
  '/events/sih-internal-hackathon/team': typeof EventsSihInternalHackathonTeamRoute
  '/events/sih-internal-hackathon/': typeof EventsSihInternalHackathonIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/projects': typeof ProjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/member/$slug': typeof MemberSlugRoute
  '/events': typeof EventsIndexRoute
  '/events/sih-internal-hackathon/join': typeof EventsSihInternalHackathonJoinRoute
  '/events/sih-internal-hackathon/team': typeof EventsSihInternalHackathonTeamRoute
  '/events/sih-internal-hackathon': typeof EventsSihInternalHackathonIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/projects': typeof ProjectsRoute
  '/events/sih-internal-hackathon': typeof EventsSihInternalHackathonRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/member/$slug': typeof MemberSlugRoute
  '/events/': typeof EventsIndexRoute
  '/events/sih-internal-hackathon/join': typeof EventsSihInternalHackathonJoinRoute
  '/events/sih-internal-hackathon/team': typeof EventsSihInternalHackathonTeamRoute
  '/events/sih-internal-hackathon/': typeof EventsSihInternalHackathonIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/auth'
    | '/events'
    | '/join'
    | '/members'
    | '/projects'
    | '/events/sih-internal-hackathon'
    | '/admin'
    | '/me'
    | '/member/$slug'
    | '/events/'
    | '/events/sih-internal-hackathon/join'
    | '/events/sih-internal-hackathon/team'
    | '/events/sih-internal-hackathon/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/auth'
    | '/join'
    | '/members'
    | '/projects'
    | '/admin'
    | '/me'
    | '/member/$slug'
    | '/events'
    | '/events/sih-internal-hackathon/join'
    | '/events/sih-internal-hackathon/team'
    | '/events/sih-internal-hackathon'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/announcements'
    | '/auth'
    | '/events'
    | '/join'
    | '/members'
    | '/projects'
    | '/events/sih-internal-hackathon'
    | '/_authenticated/admin'
    | '/_authenticated/me'
    | '/member/$slug'
    | '/events/'
    | '/events/sih-internal-hackathon/join'
    | '/events/sih-internal-hackathon/team'
    | '/events/sih-internal-hackathon/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRouteWithChildren
  JoinRoute: typeof JoinRoute
  MembersRoute: typeof MembersRoute
  ProjectsRoute: typeof ProjectsRoute
  MemberSlugRoute: typeof MemberSlugRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/sih-internal-hackathon': {
      id: '/events/sih-internal-hackathon'
      path: '/sih-internal-hackathon'
      fullPath: '/events/sih-internal-hackathon'
      preLoaderRoute: typeof EventsSihInternalHackathonRouteRouteImport
      parentRoute: typeof EventsRoute
    }
    '/member/$slug': {
      id: '/member/$slug'
      path: '/member/$slug'
      fullPath: '/member/$slug'
      preLoaderRoute: typeof MemberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/sih-internal-hackathon/': {
      id: '/events/sih-internal-hackathon/'
      path: '/'
      fullPath: '/events/sih-internal-hackathon/'
      preLoaderRoute: typeof EventsSihInternalHackathonIndexRouteImport
      parentRoute: typeof EventsSihInternalHackathonRouteRoute
    }
    '/events/sih-internal-hackathon/join': {
      id: '/events/sih-internal-hackathon/join'
      path: '/join'
      fullPath: '/events/sih-internal-hackathon/join'
      preLoaderRoute: typeof EventsSihInternalHackathonJoinRouteImport
      parentRoute: typeof EventsSihInternalHackathonRouteRoute
    }
    '/events/sih-internal-hackathon/team': {
      id: '/events/sih-internal-hackathon/team'
      path: '/team'
      fullPath: '/events/sih-internal-hackathon/team'
      preLoaderRoute: typeof EventsSihInternalHackathonTeamRouteImport
      parentRoute: typeof EventsSihInternalHackathonRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventsSihInternalHackathonRouteRouteChildren {
  EventsSihInternalHackathonJoinRoute: typeof EventsSihInternalHackathonJoinRoute
  EventsSihInternalHackathonTeamRoute: typeof EventsSihInternalHackathonTeamRoute
  EventsSihInternalHackathonIndexRoute: typeof EventsSihInternalHackathonIndexRoute
}

const EventsSihInternalHackathonRouteRouteChildren: EventsSihInternalHackathonRouteRouteChildren =
  {
    EventsSihInternalHackathonJoinRoute: EventsSihInternalHackathonJoinRoute,
    EventsSihInternalHackathonTeamRoute: EventsSihInternalHackathonTeamRoute,
    EventsSihInternalHackathonIndexRoute: EventsSihInternalHackathonIndexRoute,
  }

const EventsSihInternalHackathonRouteRouteWithChildren =
  EventsSihInternalHackathonRouteRoute._addFileChildren(
    EventsSihInternalHackathonRouteRouteChildren,
  )

interface EventsRouteChildren {
  EventsSihInternalHackathonRouteRoute: typeof EventsSihInternalHackathonRouteRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSihInternalHackathonRouteRoute:
    EventsSihInternalHackathonRouteRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRouteWithChildren,
  JoinRoute: JoinRoute,
  MembersRoute: MembersRoute,
  ProjectsRoute: ProjectsRoute,
  MemberSlugRoute: MemberSlugRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
